### ISSUE TITLE
Composer...why no tags?

### ISSUE THREAD

**Issue by dailytabs** [bshaffer/oauth2-server-bundle#13]
Problem 1
    - Installation request for bshaffer/oauth2-server-bundle dev-master -> satisfiable by bshaffer/oauth2-server-bundle[dev-master].
    - bshaffer/oauth2-server-bundle dev-master requires bshaffer/oauth2-server-php dev-master -> no matching package found.

Can't you just create a tag, like you're supposed to do?

**Comment by bshaffer** [comment]
Are you requesting a tag for this repo, or are you requesting we update the `composer.json` for _this_ repo to point to a tag in `oauth2-server-php`?

**Comment by dailytabs** [comment]
The real issue is the composer minimum-stability. It is, by default, at stable. To be compatible with your current setup, I would have to change it to dev, which I am not willing to do.

There is not a single stable, composer-installable version of your bundle!

As of now, I had to add all 3 of your projects to my composer.json (with version aliases) in order to get everything to fit together properly. At one point, I had everything installed, but noticed one class was missing an interface's method...that's when I noticed I had to use dev-develop for oauth2-server-php.

It just shouldn't be this annoying.

So, yes, I guess I am asking for a tag. A tag that works with its dependencies (who are also tagged) and installs as stable without modification and with only adding this bundle to my composer.json.

**Comment by tgalopin** [comment]
If your bundle is stable (which it seems to be), you have to tag it to have at least one version installable without `minimum-stability: dev`. I don't want to set the global `minimum-stability` as `dev` just for your bundle.

**Comment by bshaffer** [comment]
You're right.  I'll create a tag real quick which will hopefully fix this issue.  Sorry for the inconvenience.

**Comment by bshaffer** [comment]
There is now a tag `v0.1` (https://packagist.org/packages/bshaffer/oauth2-server-bundle)

Again, I apologize for the long turn around here.  Thanks for the kick in the pants.

**Comment by tgalopin** [comment]
:+1:
