### ISSUE TITLE
composer dependencies error

### ISSUE THREAD

**Issue by FrancisVarga** [bshaffer/oauth2-server-bundle#15]
did exectly what you wrote in you examples. 

``` bash
composer update bshaffer/oauth2-server-bundle
```

``` bash
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bshaffer/oauth2-server-bundle dev-master -> satisfiable by bshaffer/oauth2-server-bundle[dev-master].
    - bshaffer/oauth2-server-bundle dev-master requires bshaffer/oauth2-server-php dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by shefik** [comment]
I am experiencing the same error.

**Comment by shefik** [comment]
It appears to work if I fork "oauth2-server-bundle", and then set "repositories" in my composer file to point to the forks.

**Comment by bshaffer** [comment]
I am able to duplicate this error with the following commands:

```
$ mkdir oauth2-server-bundle-issue-15
$ cd oauth2-server-bundle-issue-15
$ echo "{}" >> composer.json
$ composer.phar require bshaffer/oauth2-server-bundle:dev-develop
```

This is strange because `dev-master` _does_ exist for `oauth2-server-php`.  Also, if you clone this project and run `composer.phar update`, the dependency matches.

I'm not sure what the issue is here.

**Comment by bshaffer** [comment]
Have you tried setting `minumum-stability` to dev in the root of your composer.json file?

``` json
{
    "minimum-stability":"dev",
    # ...
}
```

**Comment by bshaffer** [comment]
I have confirmed that by checking out to `v0.2`, this issue is now resolved.  Or, if you want to use `dev-develop` branch, you have to change your `minimum-stability` version in your project to _dev_
