### ISSUE TITLE
Client isPublic must be null for user credential

### ISSUE THREAD

**Issue by JonathanRamier** [bshaffer/oauth2-server-bundle#34]
Hi,

I tried to implement a user credential Grant type, but it's not work. When I read the doc http://bshaffer.github.io/oauth2-server-php-docs/grant-types/user-credentials/ , I saw that client ID didn't need a client secret. However, in the bundle, it's mandatory. I updated the entity doctrine client. I had

```
fields:
        client_secret:
            type:       string
            length:     40
            nullable:   true
```

**Comment by jdelaune** [comment]
Pull request for this here: #37

**Comment by bshaffer** [comment]
great catch! Thank you both. This is now merged.
