### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by Raphy** [bshaffer/oauth2-server-bundle#40]
There is a SF3 support planned here ?

**Comment by jayrulez** [comment]
bump

**Comment by Ronnie-J** [comment]
bump

**Comment by bshaffer** [comment]
This was added [here](#42) and is now supported in [composer.json](https://github.com/bshaffer/oauth2-server-bundle/blob/develop/composer.json#L21), although I have not tagged a stable release yet.

**Comment by bshaffer** [comment]
Tagged release [v0.4](https://github.com/bshaffer/oauth2-server-bundle/releases/tag/v0.4)
