### ISSUE TITLE
Undefined method errors after PR #42

### ISSUE THREAD

**Issue by guilhermednt** [bshaffer/oauth2-server-bundle#48]
I'm getting the following error on the authorization endpoint after updating to the latest commit containing PR #42:

    Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "createFromRequestStack" of class "OAuth2\HttpFoundationBridge\Request".
    Did you mean to call "createFromRequest"?

**Comment by bshaffer** [comment]
Yes, this was an oversight. Thank you for pointing out the issue, I'll cook up a fix immediately!

**Comment by bshaffer** [comment]
@guilhermednt If you update your `bshaffer/oauth2-server-httpfoundation-bridge` dependency to the latest version, that will fix your issue. I'll go ahead and tag the releases so this is more solid.

**Comment by bshaffer** [comment]
This is now fixed in `develop`
